export enum World {
    banner = "banner",
    census = "census",
    censusid = "censusid",
    censusdesc = "censusdesc",
    censusname = "censusname",
    censusranks = "censusranks",
    censusscale = "censusscale",
    censustitle = "censustitle",
    dispatch = "dispatch",
    dispatchlist = "dispatchlist",
    faction = "faction",
    factions = "factions",
    featuredregion = "featuredregion",
    happenings = "happenings",
    lastevenid = "lastevenid",
    nations = "nations",
    newnations = "newnations",
    numnations = "numnations",
    numregions = "numregions",
    poll = "poll",
    regions = "regions",
    regionsbytag = "regionsbytag",
    tgqueue = "tgqueue",
}
